# Generated by Django 4.2.7 on 2023-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=200)),
                ("lname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("passwd", models.CharField(max_length=200)),
                ("age", models.IntegerField(max_length=3)),
            ],
        ),
    ]
