# Generated by Django 4.2.7 on 2023-12-11 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_members_age"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
    ]
